import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/HomePage/Footer/Footer";
import { LoaderProvider } from "@/context/LoaderContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StarBucks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoaderProvider>
          {children}
          <Footer />
        </LoaderProvider>
      </body>
    </html>
  );
}
